site_name: Documentación Proyecto
site_url: https://oliviasgm.github.io/Documentacion_Proyecto/
docs_dir: 'docs_src'  # Directorio de documentos de origen
site_dir: 'docs'  # Directorio donde se generará el sitio web

nav:
  - Manual de Usuario: Manual_de_Usuario.md
  - Guia de Referencia: Guia_de_Referencia.md
  - Guia de Instalacion: Guia_de_Instalacion.md
  - Descarga en pdf: PDF.md

theme: 
  name: material  # Cambié el tema a 'material', ya que el de 'readthedocs' estaba dando problemas.

plugins:
  - search  # Plugin de búsqueda
  - pdf-export  # Exportación a PDF
  - with-pdf:  # Plugin para exportar documentos a PDF
      author: Olivia Susana Guziak
      copyright: CCO 1.0 Universal
      cover: true
      back_cover: false
      cover_title: Documentacion de Proyecto
      cover_subtitle: Desarrollo interfaces -2º DAM
      toc_title: Índice
      toc_level: 2
      ordered_chapter_level: 2
      output_path: pdf/Manual_de_Usuario.pdf  # Ruta de salida para el PDF

# Otros ajustes que puedes personalizar



